name: Deploy Express Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v16.14.0'

      - name: Install PM2
        run: npm install pm2 -g

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          ssh-keyscan ec2-3-109-108-180.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          ssh -T -i keyfile ubuntu@ec2-3-109-108-180.ap-south-1.compute.amazonaws.com "sudo bash deploy.sh"
